/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/alpaking.gltf
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Alpaking = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/alpaking.gltf')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[2]].reset().fadeIn(0.5).play()
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Alpaking_Evolved">
            <skinnedMesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.Alpaking_Main} skeleton={nodes.Sphere001.skeleton}>
                <meshStandardMaterial color={props.skinColor}/>
            </skinnedMesh>
            <skinnedMesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.Alpaking_Secondary} skeleton={nodes.Sphere001_1.skeleton}>
                <meshStandardMaterial color={props.headDetailColor}/>
            </skinnedMesh>
            <skinnedMesh name="Sphere001_2" geometry={nodes.Sphere001_2.geometry} material={materials.Eye_Black} skeleton={nodes.Sphere001_2.skeleton} />
            <skinnedMesh name="Sphere001_3" geometry={nodes.Sphere001_3.geometry} material={materials.Eye_White} skeleton={nodes.Sphere001_3.skeleton} />
            <skinnedMesh name="Sphere001_4" geometry={nodes.Sphere001_4.geometry} material={materials.Wings} skeleton={nodes.Sphere001_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Alpaking

useGLTF.preload('./models/alpaking.gltf')
